import { useState } from 'react';

export default function DraftEmailModal({ employee, onClose }) {
  const [copied, setCopied] = useState(false);

  const monthsSinceRaise = employee.lastRaiseDate
    ? Math.floor((new Date('2026-04-15') - new Date(employee.lastRaiseDate)) / (1000 * 60 * 60 * 24 * 30))
    : null;

  const actionSummary = employee.retentionActions.join(' ');

  const emailBody = `Subject: Retention Alert — ${employee.name} (${employee.storeName})

To: Store Manager, ${employee.storeName}

Hi Team,

I'm reaching out regarding ${employee.name} (${employee.role}) at our ${employee.storeName} location. Our Turnover Predictor has flagged them as a ${employee.flightRiskLevel} flight risk (Score: ${employee.flightRiskScore}/100) based on recent performance and schedule data.

KEY RISK INDICATORS:
${employee.riskFactors.map(f => `• ${f}`).join('\n')}

RECOMMENDED ACTIONS:
${employee.retentionActions.map(a => `• ${a}`).join('\n')}

EMPLOYEE PROFILE:
• Role: ${employee.role}
• Tenure: ${employee.daysEmployed} days (hired ${employee.hireDate})
• Current Hours: ${employee.hoursPerWeek} hrs/wk (baseline: ${employee.baselineHours} hrs/wk)
• Pay Rate: $${employee.payRate}/hr${monthsSinceRaise !== null ? `\n• Last Raise: ${monthsSinceRaise} months ago (${employee.lastRaiseDate})` : '\n• Last Raise: No raise on record'}
• Manager Rating: ${employee.managerRating}/5

ESTIMATED COST OF LOSING THIS EMPLOYEE: $3,500 in recruiting and training replacement costs.

Please take action within 48 hours and log your outreach in the HR system.

This alert was generated by the TICE Turnover Predictor — Proactive Retention Intelligence.

— TICE Operations Team`;

  function handleCopy() {
    navigator.clipboard.writeText(emailBody).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: 'rgba(0,0,0,0.75)' }}
      onClick={onClose}
    >
      <div
        className="w-full max-w-2xl rounded-xl shadow-2xl flex flex-col max-h-[90vh]"
        style={{ background: '#1B2A4A', border: '1px solid #2a4a7a' }}
        onClick={e => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div className="flex items-center justify-between p-5" style={{ borderBottom: '1px solid #2a4a7a' }}>
          <div>
            <h2 className="text-white font-bold text-base">Draft Manager Email</h2>
            <p className="text-xs mt-0.5" style={{ color: '#7fa3c8' }}>{employee.name} · {employee.storeName}</p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-white transition-colors text-xl leading-none"
          >
            ✕
          </button>
        </div>

        {/* Email Body */}
        <div className="flex-1 overflow-y-auto p-5">
          <pre
            className="text-xs whitespace-pre-wrap font-mono leading-relaxed"
            style={{ color: '#c8d8ed' }}
          >
            {emailBody}
          </pre>
        </div>

        {/* Footer Buttons */}
        <div
          className="flex gap-3 p-5 flex-wrap"
          style={{ borderTop: '1px solid #2a4a7a' }}
        >
          <button
            onClick={handleCopy}
            className="flex-1 py-2.5 rounded-lg font-semibold text-sm transition-all"
            style={{ background: copied ? '#16a34a' : '#E8792B', color: '#fff' }}
          >
            {copied ? '✓ Copied!' : 'Copy to Clipboard'}
          </button>
          <button
            onClick={onClose}
            className="px-5 py-2.5 rounded-lg font-semibold text-sm transition-colors"
            style={{ background: '#2a4a7a', color: '#c8d8ed' }}
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
